### ISSUE TITLE
Problem with using python version 3.10

### ISSUE THREAD

**Issue by shivan-s** [palewire/install-python-pipenv-pipfile#1]
Really nice workflow, although I'm getting a problem.

Here is my action:
```yml
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python, Pipenv and Pipfile packages
        uses: palewire/install-python-pipenv-pipfile@v2
        with:
          python-version: 3.10
```

I get the error message:

```

Run palewire/install-python-pipenv-pipfile@v2
  with:
    python-version: 3.1
Run actions/setup-python@v2
  with:
    python-version: 3.1
    token: ***
Version 3.1 was not found in the local cache
Error: Version 3.1 with arch x64 not found
```
I suspect the `python-version` is read as a number not a string and turns `3.10`into `3.1`.

I've submitted a PR based on the documentation, but it's untested!
