### ISSUE TITLE
Action fails (without error message)

### ISSUE THREAD

**Issue by vorburger** [palewire/install-python-pipenv-pipfile#7]
In https://github.com/google/android-fhir/pull/2513 (at commit 2fc29aa134b454013de7a86608296c495ed5f129) I've used:

```yaml
 - name: Install Python, pipenv and Pipfile packages
   uses: palewire/install-python-pipenv-pipfile@v3
   with:
      python-version: 3.12
```

and [here](https://github.com/google/android-fhir/actions/runs/8926629717/job/24518099250?pr=2513) this failed (red step) like this:

```
Run palewire/install-python-pipenv-pipfile@v3
  with:
    python-version: 3.1[2](https://github.com/google/android-fhir/actions/runs/8926629717/job/24518099250?pr=2513#step:11:2)
  env:
    GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true
    GRADLE_BUILD_ACTION_CACHE_KEY_PREFIX: fhir
    JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.10-7/x64
    GRADLE_BUILD_ACTION_SETUP_COMPLETED: true
    GRADLE_BUILD_ACTION_CACHE_RESTORED: true
    GITHUB_DEPENDENCY_GRAPH_ENABLED: true
    GITHUB_DEPENDENCY_GRAPH_JOB_CORRELATOR: build-build
    GITHUB_DEPENDENCY_GRAPH_JOB_ID: 8926629717
    GITHUB_DEPENDENCY_GRAPH_REF: refs/pull/251[3](https://github.com/google/android-fhir/actions/runs/8926629717/job/24518099250?pr=2513#step:11:3)/merge
    GITHUB_DEPENDENCY_GRAPH_SHA: 2fc29aa13[4](https://github.com/google/android-fhir/actions/runs/8926629717/job/24518099250?pr=2513#step:11:4)b454013de7a86608296c49[5](https://github.com/google/android-fhir/actions/runs/8926629717/job/24518099250?pr=2513#step:11:5)ed5f129
    GITHUB_DEPENDENCY_GRAPH_WORKSPACE: /home/runner/work/android-fhir/android-fhir
    DEPENDENCY_GRAPH_REPORT_DIR: /home/runner/work/android-fhir/android-fhir/dependency-graph-reports
Run actions/setup-python@v4
  with:
    python-version: 3.12
    cache: pipenv
    check-latest: false
    token: ***
    update-environment: true
    allow-prereleases: false
  env:
    GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true
    GRADLE_BUILD_ACTION_CACHE_KEY_PREFIX: fhir
    JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.10-7/x[6](https://github.com/google/android-fhir/actions/runs/8926629717/job/24518099250?pr=2513#step:11:6)4
    GRADLE_BUILD_ACTION_SETUP_COMPLETED: true
    GRADLE_BUILD_ACTION_CACHE_RESTORED: true
    GITHUB_DEPENDENCY_GRAPH_ENABLED: true
    GITHUB_DEPENDENCY_GRAPH_JOB_CORRELATOR: build-build
    GITHUB_DEPENDENCY_GRAPH_JOB_ID: 8926629[7](https://github.com/google/android-fhir/actions/runs/8926629717/job/24518099250?pr=2513#step:11:7)17
    GITHUB_DEPENDENCY_GRAPH_REF: refs/pull/2513/merge
    GITHUB_DEPENDENCY_GRAPH_SHA: 2fc29aa134b454013de7a[8](https://github.com/google/android-fhir/actions/runs/8926629717/job/24518099250?pr=2513#step:11:8)6608296c495ed5f129
    GITHUB_DEPENDENCY_GRAPH_WORKSPACE: /home/runner/work/android-fhir/android-fhir
    DEPENDENCY_GRAPH_REPORT_DIR: /home/runner/work/android-fhir/android-fhir/dependency-graph-reports
Installed versions
  Successfully set up CPython (3.12.3)
  
pipenv cache is not found
Run curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
  curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true
    GRADLE_BUILD_ACTION_CACHE_KEY_PREFIX: fhir
    JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.10-7/x64
    GRADLE_BUILD_ACTION_SETUP_COMPLETED: true
    GRADLE_BUILD_ACTION_CACHE_RESTORED: true
    GITHUB_DEPENDENCY_GRAPH_ENABLED: true
    GITHUB_DEPENDENCY_GRAPH_JOB_CORRELATOR: build-build
    GITHUB_DEPENDENCY_GRAPH_JOB_ID: 8[9](https://github.com/google/android-fhir/actions/runs/8926629717/job/24518099250?pr=2513#step:11:9)26629717
    GITHUB_DEPENDENCY_GRAPH_REF: refs/pull/2513/merge
    GITHUB_DEPENDENCY_GRAPH_SHA: 2fc29aa134b454013de7a86608296c495ed5f129
    GITHUB_DEPENDENCY_GRAPH_WORKSPACE: /home/runner/work/android-fhir/android-fhir
    DEPENDENCY_GRAPH_REPORT_DIR: /home/runner/work/android-fhir/android-fhir/dependency-graph-reports
    pythonLocation: /opt/hostedtoolcache/Python/3.12.3/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.12.3/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.3/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.3/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.3/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.12.3/x64/lib
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 26 21[10](https://github.com/google/android-fhir/actions/runs/8926629717/job/24518099250?pr=2513#step:11:10)k   26  558k    0     0   399k      0  0:00:05  0:00:01  0:00:04  399k
100 2[11](https://github.com/google/android-fhir/actions/runs/8926629717/job/24518099250?pr=2513#step:11:11)0k  100 2110k    0     0  1444k      0  0:00:01  0:00:01 --:--:-- 1444k
```

I'm not sure why - there is no error message.
